### ISSUE TITLE
Multiple flags not working

### ISSUE THREAD

**Issue by LuckserSky34** [HelpChat/DeluxeMenus#110]
setting the item flags like this: 
    **item_flags:
    - HIDE_ARMOR_TRIM**
don't work for some reason but when i set like this:
**item_flags: HIDE_ARMOR_TRIM**
works well but can't set more than one flag in that way

**Comment by iGabyTM** [comment]
https://github.com/HelpChat/DeluxeMenus/blame/40fa1be845fe95511a8a0f3571f360f031d1f838/src/main/java/com/extendedclip/deluxemenus/config/DeluxeMenusConfig.java#L766-L775
This is a bug, it was removed during cleanup.
