### ISSUE TITLE
ENCHANTMENTS VERSION INCOMPATIBILITY 

### ISSUE THREAD

**Issue by BadsGirl** [HelpChat/DeluxeMenus#121]
1.20.4 Paper
Deluxemenus 1.14.0

![deluxemenü](https://github.com/HelpChat/DeluxeMenus/assets/90643290/29a618f5-0aba-41f5-b812-a53d8f51a2c5)
![deluxemenü bok](https://github.com/HelpChat/DeluxeMenus/assets/90643290/fae80672-5a94-46e7-b50f-8d33417decc7)

This works in 1.20.2 - 'SILK TOUCH;1' 
but instead in 1.20.4 - DURABILITY: 1 It needs to be used, but it doesn't make the item look magical.

When you make SILK TOUCH, the error occurs as follows;
[DeluxeMenus] Enchantment SILK_TOUCH for item 2 in menu avcımenu is not a valid enchantment name!

However, when you use endurance, no error occurs, but the magical item does not appear.

I tried everything I could think of but it didn't work
I can solve the problem by downgrading the server version.

**Comment by BadsGirl** [comment]
i solved the problem

**Comment by BadsGirl** [comment]
`- SHARPNESS; 1`
When I do this an error appears in the console. How can I fix this? I managed to enchant the item but an error appears in the console.
[DeluxeMenus] Enchantment level is incorrect for item perks in menu coinshop!

**Comment by iGabyTM** [comment]
You have a space before the level, the format is `ENCHANTMENT;level`

**Comment by BadsGirl** [comment]
thanks!!

**Comment by iGabyTM** [comment]
Did that fixed your problem @BadsGirl ?

**Comment by BadsGirl** [comment]
fixed. thank you

**Comment by BlitzOffline** [comment]
> You have a space before the level, the format is `ENCHANTMENT;level`

We should probably trim white spaces for those values. Don't see a good reason not to.
