### ISSUE TITLE
%player_name% not working on spigot 1.21 

### ISSUE THREAD

**Issue by BeeAZ-pm-pl** [HelpChat/DeluxeMenus#123]
![image](https://github.com/HelpChat/DeluxeMenus/assets/89953941/7933e265-e9fd-4649-a6b2-8f05e3f3a895)

![image](https://github.com/HelpChat/DeluxeMenus/assets/89953941/97a0d85f-4562-4800-92a8-3380edbaf90d)

error detected at version DeluxeMenus-1.14.1-DEV-183, 1.14.0

**Comment by iGabyTM** [comment]
Make sure you have the expansion installed & there are no errors on startup.
