### ISSUE TITLE
Give syntax player_head with a custom name 1.20.5.

### ISSUE THREAD

**Issue by OperVaite** [HelpChat/DeluxeMenus#124]
After update 1.20.5, the syntax of the Give command has changed. I'm trying to give the player a head with a custom name, via [console] minecraft:give, it gives the error "expected <block end>, but found '['".

Full line:       - '[console] minecraft:give %player_name% minecraft:player_head[custom_name='["",{"text":"Дубовое бревно","italic":false}]',profile={properties:[{value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvM2I2NTFkMzVkMTlhNzBmMzc3MmVhNTU5NTZmMjIyNjRhMWZiMmFlZmY2OTU5YjRlMTQwNjVhOTU2OTYyOTcxYyJ9fX0=",name:textures}]}] 1'

![1](https://github.com/user-attachments/assets/7a4601d7-3052-45e9-9f38-d6cf8ae3469c)
![2](https://github.com/user-attachments/assets/3b6260eb-c245-4487-87e2-44293152ab01)

**Comment by BlitzOffline** [comment]
The issue is the fact that your strings contain quotes. This is a YAML issue rather than a DeluxeMenus one. However, to fix it, you can escape quotes in YAML like so:

```yml
 - '[console] minecraft:give %player_name% minecraft:player_head[custom_name=''["",{"text":"Дубовое бревно","italic":false}]'',profile={properties:[{value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvM2I2NTFkMzVkMTlhNzBmMzc3MmVhNTU5NTZmMjIyNjRhMWZiMmFlZmY2OTU5YjRlMTQwNjVhOTU2OTYyOTcxYyJ9fX0=",name:textures}]}] 1'
 ```
