### ISSUE TITLE
/dmenu reload does not reload menu files

### ISSUE THREAD

**Issue by SirKillian** [HelpChat/DeluxeMenus#132]
On the (current) latest dev version: (https://ci.extendedclip.com/job/DeluxeMenus/184/) the /dmenu reload command no longer reloads the menus. You need to reboot the server to apply changes.

**Comment by BlitzOffline** [comment]
Hello. I have just tested this build on Paper 1.21 and I was not able to replicate the issue. The menu reloads just fine. However, I think the issue you are experiencing might be a duplicate of https://github.com/HelpChat/DeluxeMenus/issues/3

To be able to confirm this, please send the menu that doesn't update and also the command you've tried to open the menu with. Thanks

**Comment by SirKillian** [comment]
You're correct. It's a duplicate of #3 
I must have missed this when browsing through existing issues.
