### ISSUE TITLE
MSPT 300+ OVER (getScriptEngine) [DEV BUILD 184]

### ISSUE THREAD

**Issue by GG-MD** [HelpChat/DeluxeMenus#138]
Spark: https://spark.lucko.me/qUP0rMRHEG

**Comment by iGabyTM** [comment]
Don't use the js requirement unless you __must__.
There's built-in types for the most basic requirements. Keep js as the last option.

**Comment by GG-MD** [comment]
> Don't use the js requirement unless you **must**. There's built-in types for the most basic requirements. Keep js as the last option.

This was not previously the case, will this be optimized in the future?????

**Comment by iGabyTM** [comment]
I'm not saying it is ok for the js requirement to take up this much resources. What I'm saying is that you should not use the js requirement if there is already a dedicated requirement for what you want. For example `%vault_eco_balance% > 500` can be written as a requirement with type `>` (see [the wiki](https://wiki.helpch.at/helpchat-plugins/deluxemenus/options-and-configurations/requirements#Comparators))

**Comment by GG-MD** [comment]
> I'm not saying it is ok for the js requirement to take up this much resources. What I'm saying is that you should not use the js requirement if there is already a dedicated requirement for what you want. For example `%vault_eco_balance% > 500` can be written as a requirement with type `>` (see [the wiki](https://wiki.helpch.at/helpchat-plugins/deluxemenus/options-and-configurations/requirements#Comparators))

Everything that DeluxeMenus supports is 100% utilized, unfortunately what is not possible already works via JavaScript, very much waiting for updates.

**Comment by BlitzOffline** [comment]
> > Don't use the js requirement unless you **must**. There's built-in types for the most basic requirements. Keep js as the last option.
> 
> This was not previously the case, will this be optimized in the future?????

We use an out of the box engine. We do not have our own engine. If something changed, it wasn't because of us and most likely it isn't something we can fix unfortunately. We will look into this when we have time.

**Comment by GG-MD** [comment]
> > > Don't use the js requirement unless you **must**. There's built-in types for the most basic requirements. Keep js as the last option.
> 
> > 
> 
> > This was not previously the case, will this be optimized in the future?????
> 
> 
> 
> We use an out of the box engine. We do not have our own engine. If something changed, it wasn't because of us and most likely it isn't something we can fix unfortunately. We will look into this when we have time.

The problem is yours - on older builds of your plugin everything was perfect, the most recent build currently showing a much better result, but still not perfect.
