### ISSUE TITLE
BaseHeads not working.

### ISSUE THREAD

**Issue by Tkade1** [HelpChat/DeluxeMenus#144]
BaseHeads dont work in the latest dev build (184)

material: basehead-<base64>

My example of the setup:
material: basehead-<ey0*********=>

DeluxeMenus: Dev Build -184
Server Jar: 1.20.4

**Comment by BlitzOffline** [comment]
> BaseHeads dont work in the latest dev build (184)
> 
> material: basehead-
> 
> My example of the setup: material: basehead-<ey0*********=>
> 
> DeluxeMenus: Dev Build -184 Server Jar: 1.20.4

Remove `<` and `>`.

**Comment by Tkade1** [comment]
I found the issue earlier.
My apologies for not updating the situation!

> > BaseHeads dont work in the latest dev build (184)
> > material: basehead-
> > My example of the setup: material: basehead-<ey0*********=>
> > DeluxeMenus: Dev Build -184 Server Jar: 1.20.4
> 
> Remove `<` and `>`.

**Comment by Tkade1** [comment]
I found the issue earlier.
My apologies for not updating the situation!

> > BaseHeads dont work in the latest dev build (184)
> > material: basehead-
> > My example of the setup: material: basehead-<ey0*********=>
> > DeluxeMenus: Dev Build -184 Server Jar: 1.20.4
> 
> Remove `<` and `>`.
