### ISSUE TITLE
Item Flag not working

### ISSUE THREAD

**Issue by Tkade1** [HelpChat/DeluxeMenus#145]
Server Jar: 1.20.4
DeluxeMenus: Dev Build (184)

The additional tooltip item flag is not removing the effect lore

See images for visual.
![8a5abfdfeda593e82b890e40def16e0d](https://github.com/user-attachments/assets/2d2ef3e2-d5e8-49c0-a85a-b3b8ebf02bce)
![5c011733783b0709a48aedb43be1d905](https://github.com/user-attachments/assets/5a1ffe5c-6a56-4a35-85e6-f4ac24f2e301)

**Comment by BlitzOffline** [comment]
> Server Jar: 1.20.4 DeluxeMenus: Dev Build (184)
> 
> The additional tooltip item flag is not removing the effect lore
> 
> See images for visual. ![8a5abfdfeda593e82b890e40def16e0d](https://private-user-images.githubusercontent.com/141796186/382604347-2d2ef3e2-d5e8-49c0-a85a-b3b8ebf02bce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA2NjkxODcsIm5iZiI6MTczMDY2ODg4NywicGF0aCI6Ii8xNDE3OTYxODYvMzgyNjA0MzQ3LTJkMmVmM2UyLWQ1ZTgtNDljMC1hODVhLWIzYjhlYmYwMmJjZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwM1QyMTIxMjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZTFjN2RhZTFiMWMyNjA4MzVhNzFkYzdlZmZjNTY4NTA5NWFmNmJhODBjMmUwNTAzMTlkZDBlOTZmYTI3MTU4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.-I9l4CTAbz4WA-d2mhRbd2ieeGNstgxO1Rg9x9th0S0) ![5c011733783b0709a48aedb43be1d905](https://private-user-images.githubusercontent.com/141796186/382604348-5a1ffe5c-6a56-4a35-85e6-f4ac24f2e301.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA2NjkxODcsIm5iZiI6MTczMDY2ODg4NywicGF0aCI6Ii8xNDE3OTYxODYvMzgyNjA0MzQ4LTVhMWZmZTVjLTZhNTYtNGEzNS04NWU2LWY0YWMyNGYyZTMwMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwM1QyMTIxMjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NzUyZDgyNjg4MmQzN2RjOGRlMWYwNWM1MzQ1N2VhNDYyMjg4NDkwOTZkNjdkMjM5YTY1ZTM1ZDc4MjM3ZTYyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.nEagXpW8g_IAhIG7v0rsYiUQ5Si8ZQ1FWCQbQU1wCy4)

Change the option to `item_flags`. It should contain an underscore

**Comment by Tkade1** [comment]
https://gyazo.com/33981508b8a1a5fc77da6d3e0ea47358

**Comment by Tkade1** [comment]
[DeluxeMenus] Item flag: HIDE_ADDITIONAL_TOOLTIP for item: Potions-Kit-Available in menu: kits is not a valid item flag!

**Comment by BlitzOffline** [comment]
> [DeluxeMenus] Item flag: HIDE_ADDITIONAL_TOOLTIP for item: Potions-Kit-Available in menu: kits is not a valid item flag!

Sorry for the late reply. This ItemFlag was added in 1.20.5. Is your server on 1.20.5 or higher?

**Comment by Tkade1** [comment]
It's 1.20.4, I figured out the item flag afterwards as well.
