### ISSUE TITLE
Hide attributes not working

### ISSUE THREAD

**Issue by Astolate** [HelpChat/DeluxeMenus#146]
Neither configurations is currently working to hide attributes:

```
item-flags:
  - HIDE_ATTRIBUTES
```
OR

`hide_attributes: true`

version: 1.14.0
server: Pufferfish version 1.21.1-21-HEAD@cfa3c61 (2024-10-22T23:08:19Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)

**Comment by BlitzOffline** [comment]
Change the option to `item_flags`. It should contain an underscore
