### ISSUE TITLE
Tweak message level for [refersh] action not having a menu to refresh

### ISSUE THREAD

**Issue by kristophergeou** [HelpChat/DeluxeMenus#20]
Currently all of the messages are hard coded to the plugin itself, which makes it impossible for the user to edit them, and could potentially make unnecessary spam on the console. I am talking mostly about the `[refresh]` combined with the delay for the `user doesn't have a menu open! Nothing to refresh. So in general it would he nice if we could set to empty strings things like that.

EDIT (Blitz): See here: https://github.com/HelpChat/DeluxeMenus/issues/20#issuecomment-2040222632

**Comment by BlitzOffline** [comment]
Hello @kristophergeou, that is not exactly something a lang file is meant for. Those are debug messages. We have 5 different debug levels that can be changed from the console. Tweaking that level might help you receive only more important debug messages.

**Comment by kristophergeou** [comment]
i know @BlitzOffline :/ but none of the levels remove that debug message from `[refresh]`

**Comment by BlitzOffline** [comment]
> i know @BlitzOffline :/ but none of the levels remove that debug message from `[refresh]`

I see. That message does not seem to be of the highest importance so we could lower the importance level for that message. Tweaking debug message importance is something we know is needed and have done for other messages in the past.

I will reopen this ticket as a request to change the message level.
