### ISSUE TITLE
External Configs

### ISSUE THREAD

**Issue by kristophergeou** [HelpChat/DeluxeMenus#24]
I know bliz or gaby said no when i suggested it, but i will put it out there in case anybody wants to develop it, cause why not? So basically external configs! A folder named `configs` that in there you will be able to make other unlimited secondary `config` files as a category.  Something like:
(main `config.yml) 
```yml
test_menus: 
file: config/test_menus.yml
```
instantly when the plugin checks the `config` as a folder it will go and check if in that folder there is a file named `test_menus.yml` which will be considered as an external config, that will work as if it was the default one, and load menus from there too

**Comment by broken1arrow** [comment]
If you meant categorize the menus or something else?

**Comment by kristophergeou** [comment]
nah that's already possible with the external menus, what i am suggesting it's similar to it but for configs that will load the menus inside.

**Comment by broken1arrow** [comment]
> nah that's already possible with the external menus, what i am suggesting it's similar to it but for configs that will load the menus inside.

You do you need extra config?

Make different folders for group of menus make sense. But why do you also need separate settings?

**Comment by kristophergeou** [comment]
I already have different folders to group my menus, the thing is that I ve reached 700 menus already and the main config is messy

**Comment by broken1arrow** [comment]
> I already have different folders to group my menus, the thing is that I ve reached 700 menus already and the main config is messy

I get your problem. That could be solved, but I think this will not only add complexity to the code but also to the end user.

**Comment by Kqliber** [comment]
Closing this as its unnecessary complexity just to accommodate for a small amount of people who may actually find it helpful
