### ISSUE TITLE
Add Custom material support for ExecutableItems - ExecutableBlocks

### ISSUE THREAD

**Issue by kristophergeou** [HelpChat/DeluxeMenus#26]
I saw another suggestion (#11) So pretty much something similar for these two plugins too. 
`material: ei-<item_id>`
`material: eb-<block_id>`
This one will get the material that the ID of that item/block is, and it's name and lore

ExecutableItems: https://docs.ssomar.com/executableitems/developer-api
ExecutableBlocks: https://docs.ssomar.com/executableblocks/developer-api

**Comment by Oribuin** [comment]
Added in PR #52
