### ISSUE TITLE
Request to add information function

### ISSUE THREAD

**Issue by aml2023529** [HelpChat/DeluxeMenus#68]
It is recommended to send a message with a command or enter a specific word, such as clicking on the menu to send a message whether to buy this item [OK] [Decline] Entering a specific word is to enter the world you want to teleport into.

**Comment by BlitzOffline** [comment]
Hello. I am not sure I have fully understood your request but I believe you are looking to send confirmation messages in chat, or something similar.

If this is what you are looking for, There is a plugin that adds this as a possibility. It is called CommandPrompter: https://www.spigotmc.org/resources/commandprompter.47772/. There is an example with DeluxeMenus on the spigot page of CommandPrompter.


If this is not what you want, please reopen this issue and add more information.
