### ISSUE TITLE
Placeholder double parse not working

### ISSUE THREAD

**Issue by DarkyG2** [HelpChat/DeluxeMenus#74]
I currently have a placeholder that also outputs a placeholder, for example:
%luckperms_prefix% will output "&cMVP%color_plugin%+" and and it won't parse the "%color_plugin%" placeholder for some reason

**Comment by BlitzOffline** [comment]
That is because it is up to each placeholder to parse its output if they want to. DeluxeMenus won't parse placeholder more than once.

**Comment by DarkyG2** [comment]
> That is because it is up to each placeholder to parse its output if they want to. DeluxeMenus won't parse placeholder more than once.

It's a shame since it works on 20+ plugins except Deluxemenus...
