### ISSUE TITLE
Placeholder material is updated only when reloaded

### ISSUE THREAD

**Issue by Kiuju79** [HelpChat/DeluxeMenus#75]
After upgrading from 1.13.7 to 1.14.0, Placeholder material will only be updated after reloading, which causes some issues such as (placeholder-%player_item_in_hand%) not being able to feed back in real time.

**Comment by BlitzOffline** [comment]
Hello @Kiuju79 I have not been able to replicate this issue on DeluxeMenus 1.14.1-DEV-178. Could you try this development build? You can find it here: https://ci.extendedclip.com/job/DeluxeMenus/lastStableBuild/

**Comment by Kiuju79** [comment]
Thanks, DeluxeMenus 1.14.1-DEV-178 no longer has this problem.
But when the {} of Args(Arguments) is inserted into Placeholder, it no longer seems to be parsed.

**Comment by Kiuju79** [comment]
> 您好，我无法在DeluxeMenus 1.14.1-DEV-178上复制此问题。你能试试这个开发版本吗？你可以在这里找到它：https://ci.extendedclip.com/job/DeluxeMenus/lastStableBuild/

Thanks, DeluxeMenus 1.14.1-DEV-178 no longer has this problem.
But when the {} of Args(Arguments) is inserted into Placeholder, it no longer seems to be parsed.

**Comment by BlitzOffline** [comment]
> Thanks, DeluxeMenus 1.14.1-DEV-178 no longer has this problem. But when the {} of Args(Arguments) is inserted into Placeholder, it no longer seems to be parsed.

We are aware of this issue and are investigating. If you want to follow the progress on it you can do so here: https://github.com/HelpChat/DeluxeMenus/issues/78.

I am closing this ticket since this specific issue was fixed.
