### ISSUE TITLE
Using the mod in the plugin

### ISSUE THREAD

**Issue by ragelqdev** [HelpChat/DeluxeMenus#83]
Hello, how do I use this plugin with mods? Let's say I want an item from a mod to be displayed in the menu?

**Comment by BlitzOffline** [comment]
DeluxeMenus doesn't support modded servers. It supports Spigot servers and direct forks such as Paper. We do not directly support hybrid servers such as Magma. If that server has good integration with the Spigot API, it should simply work by using `material: MATERIAL_NAME`.
