### ISSUE TITLE
Placeholders that parse with a \n do not display correctly.

### ISSUE THREAD

**Issue by Seeroh** [HelpChat/DeluxeMenus#88]
As per the title. I have a JavaScript placeholder that I made to sort and then display some player data. It has a few newline characters inside ('\n'), but DM only shows the first line of the output.

On a side note, DM also does not parse \n inside the lore, even though the wiki states that it should be able to.

**Server Version:**
git-Paper-409 (MC: 1.20.4)

**DuluxeMenus Version:**
1.14.0

**Comment by BlitzOffline** [comment]
Hello. I have tested this on the latest development build of DeluxeMenus and it does not seem to be an issue. As it can be seen in these images, only the display name is somewhat broken (it shouldn't support new lines in the first place). My assumption is that the placeholder doesn't return the new line. You can try a few things:
- test the placeholder using `/papi parse me %your_placeholder%` and see if there is the `\n` character in there
- try the latest development build from Jenkins: https://ci.extendedclip.com/job/DeluxeMenus/
- if you are not able to solve the problem, reopen this issue and send your placeholder code and your menu code

![image](https://github.com/HelpChat/DeluxeMenus/assets/52609756/ba522e68-e6e2-451d-bd73-34e0c30e63fd)
![image](https://github.com/HelpChat/DeluxeMenus/assets/52609756/36b07623-19b9-4233-b830-12143a8f3a87)

Tested on:
```
This server is running Paper version git-Paper-496 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 7ac24a1 on ver/1.20.4)
You are running the latest version
Previous version: git-Paper-365 (MC: 1.20.4)
```

```
DeluxeMenus version 1.14.1-DEV-179
Created by extended_clip, Glare
```
