### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by gazdyy** [HelpChat/DeluxeMenus#89]
'Misc':
    material: POTION
    potion_effects:
    - luck;120;10

Potion effects option doesn't work!
Server ver: paper 1.19.4
plugin ver: 1.14.0

**Comment by BlitzOffline** [comment]
I just tested your item and it worked. I suggest you try the latest development build from Jenkins: https://ci.extendedclip.com/job/DeluxeMenus/. If this doesn't fix your problem, please reopen this ticket and send full startup logs from your server together with your full menu

![image](https://github.com/HelpChat/DeluxeMenus/assets/52609756/e02f8b12-cc05-4880-af46-70ce55b5416d)

Tested on:
```
This server is running Paper version git-Paper-496 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 7ac24a1 on ver/1.20.4)
You are running the latest version
Previous version: git-Paper-365 (MC: 1.20.4)
```

```
DeluxeMenus version 1.14.1-DEV-179
Created by extended_clip, Glare
```
