### ISSUE TITLE
 1.20.5 paper is out! 

### ISSUE THREAD

**Issue by ghost** [HelpChat/DeluxeMenus#92]
https://pastebin.com/t6H5MnRD  - 1.20.5 plugin error

**Comment by Kqliber** [comment]
1.20.5 has just come out, please allow us some time so we can update the plugin.

judging by the error provided, there will be another error beforehand, which I will assume to be PlaceholderAPI failing to load at startup
As DeluxeMenus depends on PlaceholderAPI, DeluxeMenus will fail to enable.
We are aware of the issue with PlaceholderAPI and there is already a a [PR](https://github.com/PlaceholderAPI/PlaceholderAPI/pull/1035) to fix this

**Comment by BySwiizen** [comment]
1.20.6 is available.

**Comment by BySwiizen** [comment]
> 1.20.5 has just come out, please allow us some time so we can update the plugin.
> 
> judging by the error provided, there will be another error beforehand, which I will assume to be PlaceholderAPI failing to load at startup As DeluxeMenus depends on PlaceholderAPI, DeluxeMenus will fail to enable. We are aware of the issue with PlaceholderAPI and there is already a a [PR](https://github.com/PlaceholderAPI/PlaceholderAPI/pull/1035) to fix this

The PR has been merged, will you be able to update it?

**Comment by Kqliber** [comment]
Dev builds are available for PlaceholderAPI with the fix
https://ci.extendedclip.com/job/PlaceholderAPI/193/

Let me know if this helps so we can close this issue

**Comment by BySwiizen** [comment]
> Dev builds are available for PlaceholderAPI with the fix https://ci.extendedclip.com/job/PlaceholderAPI/193/
> 
> Let me know if this helps so we can close this issue

After installing the PlaceholderAPI dev build and restarting the server, it seems functional! No errors in the console and the menus seem to work correctly in game.

**Comment by addpromax** [comment]
![image](https://github.com/HelpChat/DeluxeMenus/assets/124496967/2500ebf6-f308-433d-9fb1-cc0c0d1d2016)
head is not work?
Do you have this bug?

**Comment by BlitzOffline** [comment]
I am closing this issue since the original creator has not responded in 3 weeks. We also have a confirmation of this being fixed on the latest development versions of PlaceholderAPI

@addpromax either create a new issue or ask in Discord: https://helpch.at/discord. When you do, also share more info such as your menu, your server version, your DeluxeMenus version, etc.
