### ISSUE TITLE
ArmorItem issue

### ISSUE THREAD

**Issue by iGabyTM** [HelpChat/DeluxeMenus#93]
Add version check here
https://github.com/HelpChat/DeluxeMenus/blob/8f2fa9b77c547c2d23bbd28da8c48e06b1385e49/src/main/java/com/extendedclip/deluxemenus/menu/MenuItem.java#L284

**Comment by BlitzOffline** [comment]
I did not realize ArmorMeta was introduced in 1.19.4. I will fix this.
